version: "3.9"

services:
  zio-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zio-llm-proxy
    environment:
      OPEN_AI_API_KEY: "{key}"
      SERVER_HOST: localhost
      SERVER_PORT: 8081
      SHARED_DIRECTORY_ABSOLUTE_PATH: {your_path}
      MCP_SERVERS: "{\"data\": [{\"name\": \"filesystem\", \"command\": \"docker\", \"args\": [\"run\", \"-i\", \"--rm\", \"--mount\", \"type=bind,src=${SHARED_DIRECTORY_ABSOLUTE_PATH},dst=/projects/resources\", \"mcp/filesystem\", \"/projects\"]}]}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8081"

  fe-llm-proxy:
    build:
      context: FE/.
      dockerfile: DockerfileFE
    environment:
      VITE_API_HOST: localhost
      VITE_API_PORT: 8081
    ports:
      - "4173:4173"